export const DESIGN_TOKENS = {
  colors: {
    primary: 'var(--primary-color)',
    primaryHover: 'var(--primary-hover)',
    primaryLight: 'var(--primary-light)',
    bg: 'var(--bg-color)',
    bgSecondary: 'var(--bg-secondary)',
    surface: 'var(--surface-color)',
    textMain: 'var(--text-main)',
    textMuted: 'var(--text-muted)',
    textLight: 'var(--text-light)',
    border: 'var(--border-color)',
    success: 'var(--success)',
    warning: 'var(--warning)',
    danger: 'var(--danger)',
    info: 'var(--info)',
  },
  spacing: {
    xs: 'var(--space-1)',
    sm: 'var(--space-2)',
    md: 'var(--space-3)',
    lg: 'var(--space-4)',
    xl: 'var(--space-5)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    full: 'var(--radius-full)',
  },
  shadows: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
  },
  typography: {
    display: {
      fontSize: '2rem',
      fontWeight: 800,
      lineHeight: '1.2',
      letterSpacing: '-0.025em',
      color: 'var(--text-main)',
    },
    h1: {
      fontSize: '1.5rem',
      fontWeight: 800,
      lineHeight: '1.25',
      letterSpacing: '-0.02em',
      color: 'var(--text-main)',
    },
    h2: {
      fontSize: '1.25rem',
      fontWeight: 700,
      lineHeight: '1.3',
      letterSpacing: '-0.015em',
      color: 'var(--text-main)',
    },
    h3: {
      fontSize: '1.1rem',
      fontWeight: 700,
      lineHeight: '1.35',
      letterSpacing: '-0.01em',
      color: 'var(--text-main)',
    },
    h4: {
      fontSize: '0.95rem',
      fontWeight: 700,
      lineHeight: '1.4',
      letterSpacing: '-0.01em',
      color: 'var(--text-main)',
    },
    pageHeaderTitle: {
      fontSize: '1.35rem',
      fontWeight: 800,
      lineHeight: '1.2',
      letterSpacing: '-0.02em',
      color: '#0F172A',
    },
    sectionTitle: {
      fontSize: '0.95rem',
      fontWeight: 700,
      lineHeight: '1.35',
      color: '#0F172A',
    },
    cardTitle: {
      fontSize: '0.875rem',
      fontWeight: 600,
      lineHeight: '1.4',
      color: '#1E293B',
    },
    itemTitle: {
      fontSize: '13.5px',
      fontWeight: 600,
      lineHeight: '1.35',
      color: '#1E293B',
    },
    statNumber: {
      fontSize: '1.35rem',
      fontWeight: 800,
      lineHeight: '1.1',
      color: '#0F172A',
    },
    bodyLarge: {
      fontSize: '1rem',
      fontWeight: 400,
      lineHeight: '1.5',
      color: 'var(--text-main)',
    },
    body: {
      fontSize: '0.875rem',
      fontWeight: 400,
      lineHeight: '1.5',
      color: 'var(--text-main)',
    },
    bodySmall: {
      fontSize: '0.8125rem',
      fontWeight: 400,
      lineHeight: '1.4',
      color: 'var(--text-muted)',
    },
    caption: {
      fontSize: '0.75rem',
      fontWeight: 400,
      lineHeight: '1.4',
      color: 'var(--text-muted)',
    },
    overline: {
      fontSize: '0.6875rem',
      fontWeight: 700,
      letterSpacing: '0.05em',
      textTransform: 'uppercase' as const,
    },
    buttonText: {
      fontSize: '0.875rem',
      fontWeight: 600,
      letterSpacing: '0.01em',
    },
    tableHeader: {
      fontSize: '0.75rem',
      fontWeight: 700,
      letterSpacing: '0.04em',
      textTransform: 'uppercase' as const,
      color: 'var(--text-muted)',
    },
    tableCell: {
      fontSize: '13.5px',
      fontWeight: 600,
      lineHeight: '1.4',
      color: '#0F172A',
    },
    badgeText: {
      fontSize: '0.75rem',
      fontWeight: 700,
    },
    inputLabel: {
      fontSize: '0.8125rem',
      fontWeight: 600,
      color: 'var(--text-main)',
    },
    helperText: {
      fontSize: '0.75rem',
      fontWeight: 400,
      color: 'var(--text-muted)',
    },
  },
} as const;
