export { TeacherDashboard } from './pages/TeacherDashboard';
export { TeacherProfilePage } from './pages/TeacherProfilePage';
export { MyClassesPage } from './pages/MyClassesPage';
export { StudentsDirectoryPage } from './pages/StudentsDirectoryPage';
export { TeacherAttendancePage } from './pages/TeacherAttendancePage';
export { TeacherHomeworkPage } from './pages/TeacherHomeworkPage';
export { TeacherAssignmentsPage } from './pages/TeacherAssignmentsPage';
export { TeacherMarksPage } from './pages/TeacherMarksPage';
export { TeacherAnnouncementsPage } from './pages/TeacherAnnouncementsPage';
export { TeacherEventsPage } from './pages/TeacherEventsPage';
export { TeacherCalendarPage } from './pages/TeacherCalendarPage';
export { TeacherReportsPage } from './pages/TeacherReportsPage';
export { TeacherCoursesPage } from './pages/TeacherCoursesPage';

// New Enterprise Information Architecture Modules
export { TeacherLessonPlannerPage } from './pages/TeacherLessonPlannerPage';
export { TeacherBehaviourPage } from './pages/TeacherBehaviourPage';
export { TeacherQuestionsPage } from './pages/TeacherQuestionsPage';
export { TeacherGradebookPage } from './pages/TeacherGradebookPage';
export { TeacherResourcesPage } from './pages/TeacherResourcesPage';
export { TeacherParentMeetingsPage } from './pages/TeacherParentMeetingsPage';
export { TeacherCurriculumPage } from './pages/TeacherCurriculumPage';
